### ISSUE TITLE
API name missing in 3.2.5?

### ISSUE THREAD

**Issue by arturl** [cplusplus/concurrency_ts#91]
Something looks odd in 3.2.5 para 4:

> The expression b.arrive_and_drop() shall be well-formed and have the following semantics: 

Looks like the name of the API is missing before Requires.

The same sentence is repeated in 3.2.5 para 9.

I suspect we're missing function entries for `arrive_and_name` and `arrive_and_drop`.

**Comment by alasdairmackintosh** [comment]
Added paragraphs 5 and 11 to section 3.2.5
