### ISSUE TITLE
Address comments from Jonathan Wakely

### ISSUE THREAD

**Issue by arturl** [cplusplus/concurrency_ts#94]
From: Jonathan Wakely [mailto:cxx@kayari.org] 
Sent: Thursday, April 30, 2015 16:20
To: SG1
Subject: [c++std-parallel-1546] Concerns about when_all and when_any

In the Concurrency TS WP, N4399, I'm a little concerned about the wording for when_all and when_any:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4399.html#futures.when_all

1) Notes:

1a) The Notes seem to be stating normative requirements. I'm not sure how to deduce the fact that the returned future is immediately ready from the normative wording.

1b) Independent of that, the Notes element would make more sense coming last, after the other elements (especially after the Effects element).

2) Remarks:

2a) The signature of the second overload is a forwarding reference that always moves. That allows me to pass an lvalue which will be silently moved from:

std::promise<int> p;
std::future<int> f = p.get_future();
auto f1 = when_all(f);
// f no longer valid here
p.set_value();

This is unusual, in that we don't usually silently move from lvalues.

2b) The functions will also accept const future<R>& arguments, or const future<R>&& arguments, which *cannot* be moved from!

I think the functions need better constraints, to ensure that unique future arguments are rvalues.

(I'd even consider insisting that for the first overload iterator_traits<InputIterator>::reference is an rvalue, requiring the use of something like move_iterator to wrap the iterators)

3) Effects:

3a) For the first overload it's not explicitly stated (except in the non-normative note for the empty vector case) that the size of the result vector == std::distance(first, last).

3b) Consider the example above again:

std::promise<int> p;
std::future<int> f = p.get_future();
auto f1 = when_all(f);
// f no longer valid here
p.set_value();

The Effects element says that once f is ready it gets moved into
get<0>(f1) ... that can't be right, because after the call to when_all f is not valid and will never become ready! It should talk about the shared state of f becoming ready instead of f itself. Also, the wording implies that the moving/copying happens when f becomes ready, but that would imply that some asynchronous agent modifies both f and
f1 at the call to p.set_value(). I think what it's trying to say is that f's shared state is transferred to get<0>(f1) immediately, and that when that shared state becomes ready f1 becomes ready.

3c) "The future returned by when_all will not throw an exception"
should be wording in terms of holding a value and not holding an exception, rather than throwing anything (which would only happen if someone actually called get() on it or similar).

4) Postconditions:

4a) The first postcondition doesn't make sense, valid() is a member function, what object is it being called on? (I know it means the return value, but it doesn't say that).

4b) The Postconditions talks about future<T>s and shared_future<T>s but T is not defined, and that's inconsistent with how the input futures are referred to in the rest of the specification (e.g. the Remarks talks about future<Ri>and shared_future<Ri>).

5) Returns: ... there is no Returns element

Similar problems exist for when_any:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4399.html#futures.when_any

This doesn't seem ready for PDTS to me.

**Comment by jwakely** [comment]
For 4b I think the postcondition could be worded something like:

> for each element `e` in the parameter pack `futures`, if `decay_t<decltype(e)>` is a specialization of `future` then `e.valid() == false`, otherwise `e.valid() == true`.

**Comment by arturl** [comment]
Fixed by https://github.com/cplusplus/concurrency_ts/commit/d9c3649fd667631835060db4698e21e5a1b4705d
