### ISSUE TITLE
Can is_ready by noexcept

### ISSUE THREAD

**Issue by arturl** [cplusplus/concurrency_ts#97]
Calling this function on invalid future results in UB. Can it still be noexcept?

Current wording assumes 'yes'. LWG, please advice.

**Comment by jwakely** [comment]
No, it has a "narrow contract", meaning it has preconditions on calling it, so the library guidelines say it should not be noexcept.

**Comment by viboes** [comment]
I hope one day we will get rid of these guideline. If the function has a defined behavior it can be noexcept. There is no need to enforce more constraints than needed when we already have UB.
